openapi: 3.1.0
info:
  version: 1.0.0
  title: Quotation Engine Api
  # termsOfService: https://example.com/terms/
  # contact:
  #   email: contact@example.com
  #   url: http://example.com/contact
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://apiportaluat.tuneprotect.com/apidocs/d2c/images/general-68af2602.png
  description: >
    This is an **example** API to demonstrate features of the OpenAPI
    specification.

    # Introduction

    Welcome to the brief **Quotation Engine Api** integration guide, designed to help you set up the offering our products on your platform.


    Our integrations team are at hand to support you along the way.
tags:
  - name: Token
    description: Token for authentication used for apis 
  - name: Plan price
    description: Operations about plan.
  - name: User
    description: Operations about users.
servers:
  - url: https://uat-life.tuneprotect.com/b2capi
  - url: https://life.tuneprotect.com/b2capi
paths:
  /gettoken:
    $ref: paths/token.yaml
  /getplanprice:
    $ref: paths/planprice.yaml
  /login:
    $ref: paths/user.yaml
  # /pathItem:
  #   $ref: paths/pathItem.yaml
  # /pathItemWithExamples:
  #   $ref: paths/pathItemWithExamples.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    jwt:
      description: |
        Generate your JWT from gettoken api
      type: http
      scheme: bearer
      bearerFormat: JWT
